blank_issues_enabled: true
contact_links:
  - name: Sopel's IRC channel
    url: https://webchat.freenode.net/#sopel
    about: "For more interactive help, ask in #sopel on freenode. We're usually there daily."
